<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-CJGS9IU" failures="1" tests="1" name="TestRunner.Run" time="22.305" errors="0" timestamp="2023-06-27T17:24:53 IST" skipped="0">
  <testcase classname="TestRunner.Run" name="runScenario" time="22.305">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at StepDefination.StepDef.user_can_view_confirmation_message(StepDef.java:162)
at âœ½.User can view confirmation message "The new customer has been added successfully."(file:///F:/Projects/my%20projects/BDDFramework-master/BDDFramework-master/./Features/Customer.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- TestRunner.Run -->
